### ISSUE TITLE
how to work whit two EEPROM's?

### ISSUE THREAD

**Issue by Devilscave** [sparkfun/SparkFun_External_EEPROM_Arduino_Library#13]
How do I have to set the specifications for two EEPROM's?
I need address 0x50 & 0x54

**Comment by makin-stuff** [comment]
Hi @Devilscave. To initialize communication with two Qwiic EEPROMs just call the begin function twice with the corresponding I2C addresses. This is a very basic example:

ExternalEEPROM mem1;
ExternalEEPROM mem2;

void setup() {
    mem1.begin(0x50);
    mem2.begin(0x54);
}
