### ISSUE TITLE
Linkage warnings

### ISSUE THREAD

**Issue by AJ6CU** [sparkfun/SparkFun_External_EEPROM_Arduino_Library#19]
### Your workbench
Arduino-IDE 2.0

### Steps to reproduce
Used Example 1_BasicReadWrite.ino
Board target Arduino Nano Every
Tried with V.1.0.7 and V.1.0.10  Both detail logs attached

Example compiles clean with a Arduino Nano 33 IoT target/

### Expected behavior
Would not have worried about it except candidate messages suggest a missmatched signatures

### Actual behavior
BTW: Was using V1.0.7 because I was getting a runtime failure with the basic examples  with V1.0.10 when targeting Nano and nano Every. But since I am not using the official Sparkfun board, not convinced the problem is not on my end. Again Nano and Nano Every.

Warnings with v1.0.7 and V1.0.10

[sparkfunEEPROMWarningMessages.txt] 
 (https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/files/10050226/sparkfunEEPROMWarningMessages.txt)
[sparkfunEEPROMWarningMessagesV1.0.10.txt](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/files/10050235/sparkfunEEPROMWarningMessagesV1.0.10.txt)

**Comment by nseidle** [comment]
Warnings should be fixed now in v1.0.11.

> I was getting a runtime failure with the basic examples

Feel free to open a new issue and document what you're seeing.
