### ISSUE TITLE
Arduino Nano RP2040 Connect compile error - WIRE_BUFFER_SIZE not defined

### ISSUE THREAD

**Issue by AJ6CU** [sparkfun/SparkFun_External_EEPROM_Arduino_Library#20]
### Compilation error 
Attempting to compile with RP2040 and board definition of  Arduino Nano RP2040 Arduino Mbed OS Nano Boards and getting WIRE_BUFFER_SIZE not defined.

### Your workbench
Arduino IDE 2.0.2
EEPROM Arduino Library 1.11
This "works" with Nano Every (thanks!) board definition

### Steps to reproduce
Attempt compile of Example1__BasicReadwrite  see attached compile errors with above board definitions.  Although it works with Arduino Nano RP2040 -Raspberry Pi Pico this board lacks access to pins A4-A7 that  are part of the Arduino RP2040.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead
[rp2040-compile error.txt](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/files/10050816/rp2040-compile.error.txt)

**Comment by nseidle** [comment]
Should be fixed now. Please let me know if anything else has problems.

**Comment by AJ6CU** [comment]
Thank you! Can confirm that this problem and the Nano Every warning messages have been corrected in 1.12.

Best
Mark
