### ISSUE TITLE
Erros with SparkFun Qwiic EEPROM Breakout - 512Kbit

### ISSUE THREAD

**Issue by RemyDavies** [sparkfun/SparkFun_External_EEPROM_Arduino_Library#29]
Hi all, can I please get your thoughts on this?

I'm running a SparkFun Qwiic EEPROM Breakout - 512Kbit (https://www.sparkfun.com/products/18355). It's been running for months without issue with my Arduino MKR Zero, until recently when I updated the library to v3.2.1

I've tried rolling back through previous versions but then I experience other issues.

When I run the "**Example8_InterfaceTest.ino**" - it throws many 'fails', followed by "Something went wrong. See output".

![clipboard_InterfaceTest](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/assets/96869598/d0521395-0b79-43fb-9e14-736562b4cbbc)

Similarly, the **"AutoDetectionTest.ino"** also returns an error in location 254.
![clipboard_AutoDetectionTest](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/assets/96869598/71080930-fbf1-4935-a29c-3869d33526db)

**Comment by nseidle** [comment]
Sorry for the hassle! A lot changed over the last few months but everything is pretty stable at the moment.

I've tested Ex 1 and Ex 8 using the SparkFun Qwiic EEPROM and everything works as expected.

![image](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/assets/117102/418c71e0-31e0-4878-aca6-d498c4f5974d)

![image](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/assets/117102/1a6344f3-7274-4685-a51a-e603788067ab)

![image](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/assets/117102/3ea77dd7-df14-4059-bc88-f23f441de072)

What is the output when you run Ex1? If you don't see output on Ex1, uncomment the delay(250) at the top of setup().

> When I run the "Example8_InterfaceTest.ino" - it throws many 'fails', followed by "Something went wrong. See output".

Did you set the memory type? 

    myMem.setMemoryType(512); // Valid types: 0, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048

Otherwise, it defaults to 24xx32, not 24xx512.

**Comment by RemyDavies** [comment]
Thanks for the reply! Still no luck (see below). 

I'm not missing something obvious here am I? Not sure whats going on.

Result from Ex1:
![Ex1](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/assets/96869598/3bef4cbc-fa35-45b2-ab0a-25d4dfa91845)

Result from Ex8, now with setMemoryType(512):
![Ex8](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/assets/96869598/abba679c-503a-481d-b81c-7b429ed810df)
![Clipboard03](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/assets/96869598/e34e1d87-8c3e-406b-86b0-9b333d07d183)

Result from Ex8, now with setMemoryType(512) and setMemorySizeBytes(512):
![Clipboard01](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/assets/96869598/2878609d-3fd5-4f04-818f-0a41a87839d9)
![Clipboard02](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/assets/96869598/0f1da618-8d36-446d-9597-63404dac5ebd)

**Comment by nseidle** [comment]
You are setting the memory type correctly, then you are overwriting it with these lines.

    myMem.setMemorySizeBytes(256);
    myMem.setAddressBytes(1); //Set address bytes and page size after MemorySizeBytes()
    myMem.setPageSizeBytes(1);

 You need one (setMemoryType) or the other (setMemorySizeBytes/setAddressBytes/setPageSizeBytes) but not both.

**Comment by RemyDavies** [comment]
Thank you! Ex8 passes now :)

Just to clarify - when using this EEPROM library in future, are there any other parameters (besides 'setMemoryType') that I need to initialise in setup?

I'd just like to be sure since setMemoryType wasn't required in previous versions, etc. :)

Also, any chance you may know why I'm seeing the following compile warnings?

E:\OneDrive\Documents\Arduino\libraries\SparkFun_External_EEPROM_Arduino_Library\src\SparkFun_External_EEPROM.cpp: In member function 'uint32_t ExternalEEPROM::detectMemorySizeBytes()':
E:\OneDrive\Documents\Arduino\libraries\SparkFun_External_EEPROM_Arduino_Library\src\SparkFun_External_EEPROM.cpp:593:13: warning: unused variable 'i2cAddress' [-Wunused-variable]
     uint8_t i2cAddress = settings.deviceAddress;
             ^~~~~~~~~~
E:\OneDrive\Documents\Arduino\libraries\SparkFun_External_EEPROM_Arduino_Library\src\SparkFun_External_EEPROM.cpp:626:9: warning: unused variable 'loopCount' [-Wunused-variable]
     int loopCount = 1;

**Comment by nseidle** [comment]
Very good! Thank you for opening this issue. We obviously need better documentation. I've expanded the readme and the notes on various examples. Please let me know if there's any other spots in the docs that would have made this more obvious.

Thanks for those warnings. I've removed the unused variables.

**Comment by nseidle** [comment]
Please give v3.2.2 a try and let me know if there's any other problems (in a new issue).
