### ISSUE TITLE
Spurious Serial output from ExternalEEPROM::setMemoryType for 2K EEPROMs

### ISSUE THREAD

**Issue by x86fr** [sparkfun/SparkFun_External_EEPROM_Arduino_Library#32]
Hi there,

You have an unexpected (debug?) serial output here:

https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/blob/6dd0923047498a728d2a0b25967a23ee92e83bbf/src/SparkFun_External_EEPROM.cpp#L208

Thank for your work!

**Comment by nseidle** [comment]
Thanks for reporting! And the kind words. 

Yep, I accidentally left in that print. Should be removed in the latest/next release.
