### ISSUE TITLE
compile fails with call of overloaded 'begin()' is ambiguous.

### ISSUE THREAD

**Issue by paulvha** [sparkfun/SparkFun_External_EEPROM_Arduino_Library#34]
Since the write-protect option has been added there are 2 begin() calls. 
    bool begin(uint8_t deviceAddress = 0b1010000, TwoWire &wirePort = Wire); // By default use the Wire port
    bool begin(uint8_t deviceAddress = 0b1010000, TwoWire &wirePort = Wire, uint8_t WP = 255); // By default use the Wire port

The compiler is now confused about which one to select hence the failure.

see: https://forum.sparkfun.com/viewtopic.php?f=102&t=61337

Solution : 
Remove the original begin() call (the one without WP) reference in the header and CPP file.

**Comment by nseidle** [comment]
@paulvha - thanks so much for reporting! This is what I get for merging without testing. Should be working now. Release imminent.
