### ISSUE TITLE
wire.begin() not called inside ExternalEEPROM::begin()

### ISSUE THREAD

**Issue by ebabcock72** [sparkfun/SparkFun_External_EEPROM_Arduino_Library#35]
### Subject of the issue
Every library I have used previously calls `wire.begin()` inside of the library's `begin()` function. This library requires you call `wire.begin()` prior to calling `ExternalEEPROM::begin()`. 

### Your workbench
I'm using an ESP32 board from HiLetGo powered over USB. The Sparkfun EEPROM board is wired through a Proto board and soldered wires to the I2C bus.

### Steps to reproduce
Call `ExternalEEPROM::begin()` without first calling `wire.begin()`. It fails to connect

### Expected behavior
It should connect automatically by calling `wire.begin()` itself.

### Actual behavior
Freezes and does not find the EEPROM.

**Comment by nseidle** [comment]
I'm sorry, but we stopped using a Wire.begin() inside of libraries over [four years ago](https://www.sparkfun.com/news/3245). Calling Wire.begin inside a library is a bad idea for a variety of reasons. First it overwrites any previous Wire.setClock(). Second, if a user passes in a different Wire hardware port (ie, Wire1), and the user hasn't initiated that pointer, then initiating the library with a null pointer leads to bad things.
