### ISSUE TITLE
Data location and length

### ISSUE THREAD

**Issue by zjjxxsh** [sparkfun/SparkFun_External_EEPROM_Arduino_Library#40]
##It's not a malfunction, it's a question.

How does this library work? When I am writing, I can select the data type and write easily. But when I'm reading, especially for String, how does it work to make sure that what is read is exactly the length of what I wrote before? I'd like to make sure there aren't any surprises that could happen to cause it to over-read.

**Comment by nseidle** [comment]
See the pertinent code [here](https://github.com/sparkfun/SparkFun_External_EEPROM_Arduino_Library/blob/main/src/SparkFun_External_EEPROM.cpp#L369). We are just scanning for the null terminator.
